version: '3.8'
services:
  web:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    command: sh -c "npm run ${NPM_SCRIPT:-start}"
